/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#390c00",
        "on-secondary-fixed-variant": "#2f4864",
        "surface": "#f7fafd",
        "inverse-primary": "#b3c5ff",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b3c5ff",
        "error-container": "#ffdad6",
        "surface-bright": "#f7fafd",
        "surface-container-high": "#e5e8eb",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#f8f7ff",
        "secondary-fixed-dim": "#afc9ea",
        "on-secondary-fixed": "#001d36",
        "tertiary-container": "#cc4204",
        "primary": "#0066FF",
        "surface-variant": "#e0e3e6",
        "on-background": "#181c1e",
        "primary-container": "#0066FF",
        "surface-tint": "#0066FF",
        "secondary-fixed": "#d1e4ff",
        "on-primary": "#ffffff",
        "outline-variant": "#c2c6d8",
        "on-tertiary-fixed-variant": "#832600",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#003fa4",
        "background": "#f7fafd",
        "inverse-on-surface": "#eef1f4",
        "surface-container": "#ebeef1",
        "tertiary-fixed-dim": "#ffb59d",
        "surface-container-highest": "#e0e3e6",
        "surface-dim": "#d7dadd",
        "secondary-container": "#c2dcfe",
        "on-secondary-container": "#48617e",
        "tertiary": "#a33200",
        "on-surface": "#181c1e",
        "on-primary-fixed": "#001849",
        "primary-fixed": "#dae1ff",
        "outline": "#727687",
        "tertiary-fixed": "#ffdbd0",
        "secondary": "#47607d",
        "error": "#ba1a1a",
        "on-surface-variant": "#424656",
        "on-tertiary-container": "#fff6f4",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f1f4f7"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Public Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
